#
# Common configuration for each firstwiki repo
#

permalink:        pretty

exclude: [vendor, script]

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-github-metadata

author:
  name:           FIRSTWiki Contributors
  url:            http://firstwiki.github.io
  email:

# Setup
title:            FIRSTwiki
tagline:          The FIRST Robotics encyclopedia
paginate:         5
safe:             false
excerpt_separator: ""

data_dir:         _common/_data
includes_dir:     _common/_includes
layouts_dir:      _common/_layouts

#
# Begin specific configuration for this repo
#

url:              http://firstwiki.github.io
baseurl:          /frcrules

collections:
  stronghold:
    output: true
    permalink: "/2016/:slug"
  steamworks:
    output: true
    permalink: "/2017/:slug"

#
# Defaults to make it easy to contribute new content
#

defaults:
  -
    scope:
      path: ""
      type: "stronghold"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "steamworks"
    values:
      layout: page
